services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: selfstudy
    ports:
      - "5432:5432"        # tránh xung đột nếu đang chạy Postgres local
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: minhnghiemsw@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password123
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy

  backend:
    build: .
    container_name: go_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      APP_PORT: 8080
      DB_HOST: db              # phải là tên service "db"
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password123
      DB_NAME: selfstudy
      DB_SSLMODE: disable
      DB_TIMEZONE: UTC
      JWT_SECRET: dev_secret_please_change
      ACCESS_TOKEN_TTL: 15m
      REFRESH_TOKEN_TTL: 720h
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
